themes:
  - name: "trico"
    extends: BASE_THEME_NAME
    headTags:
      # Insert <link rel="icon" href="assets/trico/images/favicons/favicon.ico" sizes="any"/> into the <head> of the page.
      - tagName: link
        attributes:
          rel: icon
          href: assets/trico/images/favicons/favicon.ico
          sizes: any